services:
  app-blue:
    build: .
    container_name: app-blue
    restart: always
    networks:
      - web

  app-green:
    build: .
    container_name: app-green
    restart: always
    networks:
      - web

networks:
  web:
    external: true